import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "node_modules/**",
    "next-env.d.ts",
    "scraper/**",
    ".venv/**",
    "venv/**",
    ".agents/**",
    // Vendored shadcn / animate-ui component code (generated by `shadcn add`).
    // Not ours to satisfy react-hooks lint rules; editing risks breaking anims.
    "src/components/animate-ui/**",
    "src/hooks/use-mobile.ts",
    "src/hooks/use-controlled-state.tsx"
  ])
]);

export default eslintConfig;
