import { describe, expect, it, vi } from "vitest";
import { discoverModels, parseOllamaModelContextLimit } from "../llm/discovery";
import type { LLMChainEntry } from "@/types";

describe("Ollama /api/show context limit resolution", () => {
  describe("parseOllamaModelContextLimit", () => {
    it("reads context_length from model_info when no num_ctx is configured", () => {
      const showData = {
        model_info: {
          "general.architecture": "llama",
          "llama.context_length": 8192
        }
      };
      expect(parseOllamaModelContextLimit(showData)).toBe(8192);
    });

    it("reads context_length with different architecture prefixes (e.g. qwen2, mistral)", () => {
      expect(
        parseOllamaModelContextLimit({
          model_info: { "qwen2.context_length": 32768 }
        })
      ).toBe(32768);

      expect(
        parseOllamaModelContextLimit({
          model_info: { "mistral.context_length": 32768 }
        })
      ).toBe(32768);

      expect(
        parseOllamaModelContextLimit({
          model_info: { context_length: 16384 }
        })
      ).toBe(16384);
    });

    it("allows configured num_ctx in parameters to override model_info.context_length", () => {
      const showData = {
        parameters: "num_ctx                       4096\nnum_keep                       24",
        model_info: {
          "general.architecture": "llama",
          "llama.context_length": 8192
        }
      };
      // num_ctx 4096 overrides 8192
      expect(parseOllamaModelContextLimit(showData)).toBe(4096);
    });

    it("allows configured num_ctx in modelfile to override model_info.context_length", () => {
      const showData = {
        modelfile: '# Modelfile generated by "ollama show"\nFROM llama3:latest\nPARAMETER num_ctx 4096\nPARAMETER stop "<|eot_id|>"',
        model_info: {
          "llama.context_length": 131072
        }
      };
      // num_ctx 4096 overrides 131072
      expect(parseOllamaModelContextLimit(showData)).toBe(4096);
    });

    it("prefers parameters num_ctx if both parameters and modelfile specify num_ctx", () => {
      const showData = {
        parameters: "num_ctx 2048",
        modelfile: "PARAMETER num_ctx 4096",
        model_info: {
          "llama.context_length": 8192
        }
      };
      expect(parseOllamaModelContextLimit(showData)).toBe(2048);
    });

    it("returns undefined when no context limit information is present", () => {
      expect(parseOllamaModelContextLimit({})).toBeUndefined();
      expect(parseOllamaModelContextLimit({ parameters: "temperature 0.7" })).toBeUndefined();
      expect(parseOllamaModelContextLimit({ model_info: { "general.architecture": "llama" } })).toBeUndefined();
    });
  });

  describe("discoverModels with Ollama provider", () => {
    it("calls /api/show for discovered models and attaches the effective contextLimit", async () => {
      const entry: LLMChainEntry = {
        provider: "ollama",
        model: "",
        keySource: "none",
        baseUrl: "http://localhost:11434"
      };

      const mockFetch = vi.fn().mockImplementation(async (url: string, init?: RequestInit) => {
        const urlStr = String(url);
        if (urlStr.endsWith("/api/tags")) {
          return {
            ok: true,
            status: 200,
            json: async () => ({
              models: [
                { name: "llama3:latest", model: "llama3:latest" },
                { name: "mistral:custom", model: "mistral:custom" }
              ]
            })
          };
        }

        if (urlStr.endsWith("/api/show")) {
          const body = JSON.parse(String(init?.body ?? "{}"));
          if (body.model === "llama3:latest") {
            // num_ctx overrides model_info.context_length
            return {
              ok: true,
              status: 200,
              json: async () => ({
                parameters: "num_ctx 4096\nstop <|eot_id|>",
                model_info: { "llama.context_length": 8192 }
              })
            };
          }
          if (body.model === "mistral:custom") {
            // Native model_info context_length without num_ctx override
            return {
              ok: true,
              status: 200,
              json: async () => ({
                model_info: { "mistral.context_length": 32768 }
              })
            };
          }
        }

        return { ok: false, status: 404, json: async () => ({}) };
      });

      const models = await discoverModels(entry, mockFetch as unknown as typeof fetch);

      expect(models).toHaveLength(2);
      expect(models[0]).toEqual({
        id: "llama3:latest",
        name: "llama3:latest",
        contextLimit: 4096 // num_ctx override applied
      });
      expect(models[1]).toEqual({
        id: "mistral:custom",
        name: "mistral:custom",
        contextLimit: 32768 // model_info.context_length read
      });

      // Verify POST /api/show calls
      const showCalls = mockFetch.mock.calls.filter(([u]) => String(u).endsWith("/api/show"));
      expect(showCalls).toHaveLength(2);
      expect(JSON.parse(showCalls[0][1].body)).toEqual({ model: "llama3:latest" });
      expect(JSON.parse(showCalls[1][1].body)).toEqual({ model: "mistral:custom" });
    });
  });
});
